# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_UPLOADS_SOURCE)%'
        uploads.storage.local:
            adapter: 'local'
            public_url: '%env(BASE_URL)%'
            options:
                directory: '%upload_directory%'
        uploads.storage.aws:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: 'upload'
                prefix: 'myprefix'

