version: '3.5'
services:
  nginx:
    container_name: nginx
    volumes:
      - ./../:/var/www/site
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    image: nginx
    ports:
      - "8081:80"
    links:
      - fpm
    networks:
      - net
  fpm:
    container_name: fpm
    build:
      context: ./fpm
      args:
        - UID
        - USER_NAME
    user: ${USER_NAME}
    working_dir: /var/www/site
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./../:/var/www/site
      - ./fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - net
  mysql:
    container_name: mysql
    image: mariadb:10.4.12-bionic
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - 3307:3306
    networks:
      - net
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8026:8025
    networks:
      - net
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9190" --address ":9100"
    restart: always
    ports:
      - 9100:9000
      - 9190:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=secret123
    networks:
      - net
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "2020:5672"
      - "3030:15672"
    networks:
      - net
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
networks:
  net:
    name: network
    ipam:
      driver: default